
#[[main]]
#  name = "Velkommen"
#  url = "#about"
#  weight = 10

[[main]]
  name = "Damer"
  url = "#damer"
  weight = 40

[[main]]
  name = "Herrer"
  url = "#herre"
  weight = 45

[[main]]
  name = "Bestyrelsen"
  url = "#bestyrelsen"
  weight = 46

[[main]]
  name = "Tr√¶ningstider"
  url = "#traeningstider"
  weight = 50

[[main]]
  name = "Foreningsmotion"
  url = "#documents"
  weight = 55

[[main]]
  name = "Kontakt"
  url = "#contact"
  weight = 60


#################


[[main_right]]
  name = "Tilmeld"
  url = "/tilmeld/"
  weight = 50

[[main_right]]
  name = "Sponsorer"
  url = "/sponsorer/"
  weight = 55